project:
  type: website
  output-dir: _book/slides
  render:
    - "demo/03-01-open-model-view/index.qmd"
    - "demo/03-02-add-datasets/index.qmd"
    - "demo/03-03-combine-classes/index.qmd"
    - "demo/03-04-transform-no-veg/index.qmd"
    - "demo/03-05-transform-veg/index.qmd"
    - "demo/03-06-expression/index.qmd"
    - "demo/03-07-merge/index.qmd"
    - "demo/03-08-convert/index.qmd"
    - "demo/03-09-outputs/index.qmd"
    - "demo/03-10-map-view/index.qmd"
    - "demo/03-11-agc-uncertainty-carbon/index.qmd"
    - "demo/03-12-agc-uncertainty-measurement/index.qmd"
    - "demo/03-13-agc-uncertainty-false/index.qmd"
    - "demo/03-14-agc-uncertainty-habitat/index.qmd"
    - "demo/03-15-merge-uncertainty/index.qmd"
    - "demo/03-16-uncertainty-wld/index.qmd"
    - "demo/05-01-explore/index.qmd"
    - "demo/05-02-refine/index.qmd"
    - "demo/05-03-exclude/index.qmd"
    - "demo/05-04-proximity/index.qmd"
    - "demo/05-05-fragmentation/index.qmd"
    - "demo/05-06-continuity/index.qmd"
    - "demo/05-07-continuity-mod/index.qmd"
    - "demo/05-08-combining/index.qmd"

format:
  revealjs:
    theme: [default]
