project:
  type: book
  output-dir: _book
  pre-render: quarto render --profile slides

book:
  title: "LIMMMA Documentation"
  chapters:
    - index.qmd
    - 01-key-features.qmd
    - 02-getting-started.qmd
    - 03-use-agc.qmd
    - 04-use-bgc.qmd
    - 05-use-mfl.qmd
    - 06-use-ai.qmd
    - glossary.qmd

format:
  html:
    theme: cosmo
    lightbox: true

margin-header: |
  ![](/images/logos/LIMMMA-Logo.png)
