# Introduction {.unnumbered}

The University of Sussex [LIMMMA](https://landscapes.wearepal.ai/) tool (Landscape Integrative Mapping and Modelling for Multifunctional Analysis) is an evolving project that began in 2017 with a new multi-disciplinary collaboration between the University's Science Policy Research Unit ([SPRU](https://www.sussex.ac.uk/business-school/people-and-departments/spru)) and the Predictive Analytics Lab ([PAL](https://wearepal.ai)) within the Informatics department.

This initial proof of concept stage of development was funded by the University of Sussex's [SSRP](https://www.sussex.ac.uk/research/centres/sussex-sustainability-research-programme/) initiative (Sussex Sustainability Research Programme). Just as machine learning and AI was beginning to be applied more widely to computer vision problems such as object detection and image segmentation this project brought together a core team of researchers to develop a web-application to enable AI-assisted land cover and land use classification for geospatial analysis.
By collaborating across the traditional separation between social science and engineering we were able create a bespoke tool for non-expert users to generate and analyse LULC (land use land cover) maps from satellite imagery in peri-urban contexts where conventional methods of land cover classification break down due to the complexity of the landscape.

The British Academy funded our team to continue development of the tool as part of an interdisciplinary research project titled [“Inclusive Green Infrastructures for Urban Wellbeing”](https://agri-food-transformations.netlify.app/) under the British Academy Urban Infrastructures of Well-being Programme.
During this phase of development, a prototype modelling system was built into the tool to enable the analysis of land use changes over time and to implement a scoring system to visualise the impacts of those changes on different stakeholders.

Subsequently, our team joined a large consortium project to apply and further develop the LIMMMA tool to support decision and policy making around nature recovery, nature based solutions and multifunctional landscape strategies. This is a £12.5 billion pilot project called ["Nature Based Solutions for Climate Change at the Landscape Level"](https://naturalengland.blog.gov.uk/2021/07/23/nature-based-solutions-for-climate-change-at-the-landscape-scale-a-new-12-5m-pilot-programme/) funded by the Joint Treasury Outcome Fund. It runs from 2021-2025 and is led by Natural England and the Sussex team co-Is (working directly with Kew Science) are Fiona Marshall, Novi Quadrianto, Jeremy Reffin.

During this project we completely rebuilt the LIMMMA tool to enhance and fully integrate the mapping, modelling and AI elements. Alongside this we worked with scientists at Kew to use LIMMMA to support their emerging work on landscape-based carbon and biodiversity monitoring and modelling. The culmination of this work is the LIMMMA tool presented in this documentation. However, it is not simply a finished piece of software but is part of an ongoing transdisciplinary research effort to support creative engagement over landscape management strategies between multiple stakeholders from policy makers to local communities and scientific researchers. As such, we see LIMMMA as an evolving platform around which to gather these diverse stakeholders for engagement with emerging evidence and differing values and assumptions about how we want to improve our local and national landscapes.

Notes

Biological, social and physical sciences – community engaged.
Landscape change – ecosystem services, well-being, livelihoods.
Critical transition zones – impact of 'sustainability' interventions.
Understanding use of different system framings and forms of knowledge/evidence across scales.
Decision making for resilient future landscapes which support ecosystem services and wellbeing.

Understanding the changing function and value of multifunctional landscapes and how they are shaped.
Build up detailed multifunctional landscape mosaic of social, cultural, biophysical and economic issues associated with the suitability and impact of NbS/nature recovery. (Connectivities, co-benefits, trade-offs)
Strong contextual foundation for utilizing emerging science from Nature Returns and others.
Increased involvement of local communities including citizen science.
Sharing lessons from NbS interventions over the long-term.
Support and contextualise NbS policy and plans and their evaluation.
Gain real-time feedback from policy interventions.
Scale up lessons from pilot site living labs.
